# Generated by Django 5.2.6 on 2025-12-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addpersonaldetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nationality', models.CharField(max_length=150)),
                ('State', models.CharField(max_length=150)),
                ('District', models.CharField(max_length=150)),
                ('DOB', models.DateField()),
                ('Address', models.CharField(max_length=1000)),
                ('Religion', models.CharField(max_length=150)),
                ('Sex', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('University', models.CharField(blank=True, max_length=100, null=True)),
                ('Institute', models.CharField(blank=True, max_length=100, null=True)),
                ('CourseName', models.CharField(max_length=150)),
                ('Duration', models.CharField(max_length=150)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=150)),
                ('Field', models.CharField(max_length=150)),
                ('Duration', models.CharField(max_length=150)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
            ],
        ),
    ]
