# Generated by Django 5.2.6 on 2025-12-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_addpersonaldetail_education_workexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='Company',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='Duration',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='EndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='Field',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='StartDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
