# Generated by Django 5.2.6 on 2025-12-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_workexperience_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='Status',
            field=models.CharField(choices=[('working', 'Working'), ('not_working', 'Not Working')], default='working', max_length=20),
        ),
    ]
