# Generated by Django 5.2.6 on 2025-12-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_crtification_language_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=200)),
                ('Emailaddress', models.CharField(max_length=300)),
                ('Subject', models.CharField(max_length=1000)),
                ('Message', models.TextField()),
            ],
        ),
    ]
